### ISSUE TITLE
can't get it to work with tmp101 i2c 

### ISSUE THREAD

**Issue by zSaaiq** [arouanet/homebridge-sht3x#1]
Hello i'm new to the Project Homebridge. i just tried the half day to get this to work with an TMP101 Temperatur sensor from Texas instruments (http://www.ti.com/lit/ds/symlink/tmp100.pdf) but still no luck. i'm stuck at "EREMOTEIO: remote I/O error, write" when i start my Homebridge .. is this because the TMP101 has no Humidity feature ? can u help me to get this to work?

**Comment by arouanet** [comment]
Hi @zSaaiq,
This plugin only supports the Sensirion SHT3x sensor series. The Texas Instruments TMP101 is a completely different sensor, which uses a different I²C protocol. Supporting it would require writing a separate module to communicate with the device, and is out of scope for this project.
